export const THEMES = {
  dark: {
    nombre: "Oscuro",
    colores: {
      "color-fondo": "#242424",
      "color-negro": "#000000",
      "color-borde-modal": "#cccccc",
      "color-fondo-overlay": "#000000cd",
      "color-fondo-modal": "#000000",
      "color-fondo-botones": "#1a1a1a",
      "color-fondo-botones-focus": "#ffffff",
      "color-fondo-grafica": "#1a1a1a",
      "color-texto": "#ffffff",
      "color-texto-primario": "#61dafb",
      "color-ingreso": "#008000",
      "color-gasto": "#ff0000",
      "color-cancelar": "#8b0000",
      "color-cancelar-focus": "#ad2f2f",
      "color-fondo-swipe": "#ffffff1f",
    },
  },

  light: {
    nombre: "Claro",
    colores: {
      "color-fondo": "#f5f5f5",
      "color-negro": "#ffffff",
      "color-borde-modal": "#333",
      "color-fondo-overlay": "#ffffffcc",
      "color-fondo-modal": "#ffffff",
      "color-fondo-botones": "#ffffff",
      "color-fondo-botones-focus": "#86e7ff",
      "color-fondo-grafica": "#ffffff",
      "color-texto": "#000000",
      "color-texto-primario": "#1976d2",
      "color-ingreso": "#2e7d32",
      "color-gasto": "#d32f2f",
      "color-cancelar": "#a34444",
      "color-cancelar-focus": "#b71c1c",
      "color-fondo-swipe": "#0000001f",
    },
  },

  pink: {
    nombre: "Rosa",
    colores: {
      "color-fondo": "#dc98ca",
      "color-negro": "#ffffff",
      "color-borde-modal": "#44143c",
      "color-fondo-overlay": "#490960cc",
      "color-fondo-modal": "#490960",
      "color-fondo-botones": "#da55bf",
      "color-fondo-botones-focus": "#a4239c",
      "color-fondo-grafica": "#640b51",
      "color-texto": "#ffffff",
      "color-texto-primario": "#ff9eef",
      "color-ingreso": "#ff00bb",
      "color-gasto": "#7a085a",
      "color-cancelar": "#9e0057",
      "color-cancelar-focus": "#3c0030",
      "color-fondo-swipe": "#5b00521f",
    },
  },
};
