export const THEMES = {
  dark: {
    nombre: "Oscuro",
    colores: {
      "color-fondo": "#242424",
      "color-input": "#000000",
      "color-borde-modal": "#cccccc",
      "color-fondo-overlay": "#000000cd",
      "color-fondo-modal": "#000000",
      "color-fondo-botones": "#1a1a1a",
      "color-fondo-botones-focus": "#ffffff",
      "color-fondo-grafica": "#1a1a1a",
      "color-texto": "#ffffff",
      "color-texto-primario": "#61dafb",
      "color-ingreso": "#008000",
      "color-gasto": "#ff0000",
      "color-cancelar": "#8b0000",
      "color-cancelar-focus": "#ad2f2f",
      "color-fondo-swipe": "#ffffff1f",
    },
  },

  light: {
    nombre: "Claro",
    colores: {
      "color-fondo": "#f5f5f5",
      "color-input": "#ffffff",
      "color-borde-modal": "#333",
      "color-fondo-overlay": "#ffffffcc",
      "color-fondo-modal": "#ffffff",
      "color-fondo-botones": "#ffffff",
      "color-fondo-botones-focus": "#86e7ff",
      "color-fondo-grafica": "#ffffff",
      "color-texto": "#000000",
      "color-texto-primario": "#1976d2",
      "color-ingreso": "#2e7d32",
      "color-gasto": "#d32f2f",
      "color-cancelar": "#a34444",
      "color-cancelar-focus": "#b71c1c",
      "color-fondo-swipe": "#0000001f",
    },
  },

  pink: {
    nombre: "Barbie",
    colores: {
      "color-fondo": "#e196cd",
      "color-input": "#310442",
      "color-borde-modal": "#91167c",
      "color-fondo-overlay": "#490960cc",
      "color-fondo-modal": "#310442",
      "color-fondo-botones": "#da55bf",
      "color-fondo-botones-focus": "#a4239c",
      "color-fondo-grafica": "#640b51",
      "color-texto": "#ffd4e9",
      "color-texto-primario": "#bf009f",
      "color-ingreso": "#ff00bb",
      "color-gasto": "#ba024c",
      "color-cancelar": "#710028",
      "color-cancelar-focus": "#9e003d",
      "color-fondo-swipe": "#5b00521f",
    },
  },

  summer: {
    nombre: "Verano",
    colores: {
      "color-fondo": "linear-gradient(135deg, #ec9157, #35279d)",
      "color-input": "#2c699e",
      "color-borde-modal": "#2bb6fb",
      "color-fondo-overlay": "#a0cff59b",
      "color-fondo-modal": "#22598a",
      "color-fondo-botones": "#be7e2f",
      "color-fondo-botones-focus": "#77400c",
      "color-fondo-grafica": "#77400c78",
      "color-texto": "#ffffff",
      "color-texto-primario": "#6ed1ff",
      "color-ingreso": "#ffbb4f",
      "color-gasto": "#2769c5",
      "color-cancelar": "#874d0b",
      "color-cancelar-focus": "#9e4500",
      "color-fondo-swipe": "#5b2a001f",
    },
  },
};
